In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
df=pd.read_csv("./data/loan_approval_dataset.csv")
df.head()

,loan_id,no_of_dependents,education,self_employed,income_annum,loan_amount,loan_term,cibil_score,residential_assets_value,commercial_assets_value,luxury_assets_value,bank_asset_value,loan_status
0,1,2,Graduate,No,9600000,29900000,12,778,2400000,17600000,22700000,8000000,Approved
1,2,0,Not Graduate,Yes,4100000,12200000,8,417,2700000,2200000,8800000,3300000,Rejected
2,3,3,Graduate,No,9100000,29700000,20,506,7100000,4500000,33300000,12800000,Rejected
3,4,3,Graduate,No,8200000,30700000,8,467,18200000,3300000,23300000,7900000,Rejected
4,5,5,Not Graduate,Yes,9800000,24200000,20,382,12400000,8200000,29400000,5000000,Rejected

In [3]:
df.columns=df.columns.str.strip()

In [4]:
df.shape

(4269, 13)

In [5]:
df.describe().T

,count,mean,std,min,25%,50%,75%,max
loan_id,4269.0,2.135000e+03,1.232498e+03,1.0,1068.0,2135.0,3202.0,4269.0
no_of_dependents,4269.0,2.498712e+00,1.695910e+00,0.0,1.0,3.0,4.0,5.0
income_annum,4269.0,5.059124e+06,2.806840e+06,200000.0,2700000.0,5100000.0,7500000.0,9900000.0
loan_amount,4269.0,1.513345e+07,9.043363e+06,300000.0,7700000.0,14500000.0,21500000.0,39500000.0
loan_term,4269.0,1.090045e+01,5.709187e+00,2.0,6.0,10.0,16.0,20.0
cibil_score,4269.0,5.999361e+02,1.724304e+02,300.0,453.0,600.0,748.0,900.0
residential_assets_value,4269.0,7.472617e+06,6.503637e+06,-100000.0,2200000.0,5600000.0,11300000.0,29100000.0
commercial_assets_value,4269.0,4.973155e+06,4.388966e+06,0.0,1300000.0,3700000.0,7600000.0,19400000.0
luxury_assets_value,4269.0,1.512631e+07,9.103754e+06,300000.0,7500000.0,14600000.0,21700000.0,39200000.0
bank_asset_value,4269.0,4.976692e+06,3.250185e+06,0.0,2300000.0,4600000.0,7100000.0,14700000.0

In [6]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4269 entries, 0 to 4268
Data columns (total 13 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   loan_id                   4269 non-null   int64
 1   no_of_dependents          4269 non-null   int64
 2   education                 4269 non-null   object
 3   self_employed             4269 non-null   object
 4   income_annum              4269 non-null   int64
 5   loan_amount               4269 non-null   int64
 6   loan_term                 4269 non-null   int64
 7   cibil_score               4269 non-null   int64
 8   residential_assets_value  4269 non-null   int64
 9   commercial_assets_value   4269 non-null   int64
 10  luxury_assets_value       4269 non-null   int64
 11  bank_asset_value          4269 non-null   int64
 12  loan_status               4269 non-null   object
dtypes: int64(10), object(3)
memory usage: 433.7+ KB

In [7]:
#Check missing values
df.isna().sum()

loan_id                     0
no_of_dependents            0
education                   0
self_employed               0
income_annum                0
loan_amount                 0
loan_term                   0
cibil_score                 0
residential_assets_value    0
commercial_assets_value     0
luxury_assets_value         0
bank_asset_value            0
loan_status                 0
dtype: int64

In [8]:
#Get categorical columns
cat_col=df.select_dtypes(include="object").columns.to_list()
cat_col

['education', 'self_employed', 'loan_status']

In [9]:
for i in cat_col:
    print(f"{i}:unique values:{df[i].unique()}")

education:unique values:[' Graduate' ' Not Graduate']
self_employed:unique values:[' No' ' Yes']
loan_status:unique values:[' Approved' ' Rejected']

In [10]:
#Get the  numerical columns
num_cols=df.select_dtypes(exclude="object").columns.to_list()
num_cols

['loan_id',
 'no_of_dependents',
 'income_annum',
 'loan_amount',
 'loan_term',
 'cibil_score',
 'residential_assets_value',
 'commercial_assets_value',
 'luxury_assets_value',
 'bank_asset_value']

In [11]:
df.columns.to_list()
df[ "no_of_dependents"]

0       2
1       0
2       3
3       3
4       5
       ..
4264    5
4265    0
4266    2
4267    1
4268    1
Name: no_of_dependents, Length: 4269, dtype: int64

In [12]:
df[num_cols[0]]

0          1
1          2
2          3
3          4
4          5
        ...
4264    4265
4265    4266
4266    4267
4267    4268
4268    4269
Name: loan_id, Length: 4269, dtype: int64

In [13]:
#outlier checking function
def find_outliers(sr,col):
    Q1=sr[col].quantile(0.25)
    Q3=sr[col].quantile(0.75)
    IQR=Q3-Q1
    lower_bound=Q1-1.5*IQR
    upper_bound=Q3+1.5*IQR
    outlier_iqr1=(sr[col]<lower_bound) | (sr[col]>upper_bound)
    print(f"{col}:{len(sr[outlier_iqr1])}")
    return outlier_iqr1
outliers=df["loan_id"]<-1
for i in num_cols:
    outliers=outliers|(find_outliers(df,i))

loan_id:0
no_of_dependents:0
income_annum:0
loan_amount:0
loan_term:0
cibil_score:0
residential_assets_value:52
commercial_assets_value:37
luxury_assets_value:0
bank_asset_value:5

In [14]:
c=0
for i in outliers:
    if i==True:
        c+=1
print(c)
len(df[outliers])

91

91

In [15]:
print(len(df[outliers==True]))
#remove outliers from numerical columns
df=df[~(outliers)]
print(len(df[outliers==True]))

91
0

/tmp/ipykernel_372132/2394595288.py:4: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  print(len(df[outliers==True]))

In [16]:
print(cat_col)
for i in cat_col:
    print(f"{i}:unique values:{df[i].unique()}")

['education', 'self_employed', 'loan_status']
education:unique values:[' Not Graduate' ' Graduate']
self_employed:unique values:[' Yes' ' No']
loan_status:unique values:[' Rejected' ' Approved']

In [17]:
df.drop("loan_id",axis=1,inplace=True)
df.head()

,no_of_dependents,education,self_employed,income_annum,loan_amount,loan_term,cibil_score,residential_assets_value,commercial_assets_value,luxury_assets_value,bank_asset_value,loan_status
1,0,Not Graduate,Yes,4100000,12200000,8,417,2700000,2200000,8800000,3300000,Rejected
2,3,Graduate,No,9100000,29700000,20,506,7100000,4500000,33300000,12800000,Rejected
3,3,Graduate,No,8200000,30700000,8,467,18200000,3300000,23300000,7900000,Rejected
4,5,Not Graduate,Yes,9800000,24200000,20,382,12400000,8200000,29400000,5000000,Rejected
5,0,Graduate,Yes,4800000,13500000,10,319,6800000,8300000,13700000,5100000,Rejected

In [18]:
df["loan_status"]=df["loan_status"].map({" Rejected":0," Approved":1})
df.head()

,no_of_dependents,education,self_employed,income_annum,loan_amount,loan_term,cibil_score,residential_assets_value,commercial_assets_value,luxury_assets_value,bank_asset_value,loan_status
1,0,Not Graduate,Yes,4100000,12200000,8,417,2700000,2200000,8800000,3300000,0
2,3,Graduate,No,9100000,29700000,20,506,7100000,4500000,33300000,12800000,0
3,3,Graduate,No,8200000,30700000,8,467,18200000,3300000,23300000,7900000,0
4,5,Not Graduate,Yes,9800000,24200000,20,382,12400000,8200000,29400000,5000000,0
5,0,Graduate,Yes,4800000,13500000,10,319,6800000,8300000,13700000,5100000,0

In [19]:
df.to_csv("./data/processed_loan_dataset.csv",index=False)

In [21]:
from sklearn.preprocessing import OneHotEncoder
encoder=OneHotEncoder(drop='if_binary', sparse_output=False)

In [22]:
encoded_array=encoder.fit_transform(df[cat_col])

In [24]:
encoded_df = pd.DataFrame(encoded_array, columns=encoder.get_feature_names_out(df[cat_col].columns))
encoded_df.head(10)

   education_ Not Graduate  self_employed_ Yes  loan_status_ Rejected
0                      1.0                 1.0                    1.0
1                      0.0                 0.0                    1.0
2                      0.0                 0.0                    1.0
3                      1.0                 1.0                    1.0
4                      0.0                 1.0                    1.0
5                      0.0                 0.0                    0.0
6                      0.0                 1.0                    1.0
7                      0.0                 1.0                    0.0
8                      1.0                 0.0                    1.0
9                      0.0                 1.0                    0.0

In [85]:
#one hot encode categorical columns
df["education"]=df["education"].map({" Not Graduate":0," Graduate":1})
df["self_employed"]=df["self_employed"].map({' Yes':1,' No':0})
df["loan_status"]=df["loan_status"].map({" Rejected":0," Approved":1})
df.head()

,loan_id,no_of_dependents,education,self_employed,income_annum,loan_amount,loan_term,cibil_score,residential_assets_value,commercial_assets_value,luxury_assets_value,bank_asset_value,loan_status
1,2,0,0,1,4100000,12200000,8,417,2700000,2200000,8800000,3300000,0
2,3,3,1,0,9100000,29700000,20,506,7100000,4500000,33300000,12800000,0
3,4,3,1,0,8200000,30700000,8,467,18200000,3300000,23300000,7900000,0
4,5,5,0,1,9800000,24200000,20,382,12400000,8200000,29400000,5000000,0
5,6,0,1,1,4800000,13500000,10,319,6800000,8300000,13700000,5100000,0

In [88]:
df.to_csv("./data/processed_loan_dataset.csv",index=False)